environment:
  nuget_apikey:
    secure: oy2ndktws5wfdmswp6aq44r3dal5nk7ebdqjhlmmqbjkwi
image: WMF 5
install:
- ps: .\buildscripts\install.ps1
build_script:
- ps: .\buildscripts\build.ps1
test_script:
- ps: .\buildscripts\test.ps1
after_test:
- ps: .\buildscripts\publish.ps1